server:
  port: 8085

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: sth@gmail.com
    password: 1234567890
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  datasource:
    url: jdbc:postgresql://localhost:5432/nexushr
    username: postgres
    password: root

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true