version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: nexushr
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  auth-service:
    image: varshith1001/auth-service:latest
    restart: unless-stopped
    container_name: auth-service
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: nexushr
      DB_USERNAME: postgres
      DB_PASSWORD: root
    depends_on:
      - postgres

  employee-service:
    image: varshith1001/employee-service:latest
    restart: unless-stopped
    container_name: employee-service
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: nexushr
      DB_USERNAME: postgres
      DB_PASSWORD: root
      JWT_SECRET: mysecretkeymysecretkeymysecretkey123456
    depends_on:
      - postgres
      - redis

  payroll-service:
    image: varshith1001/payroll-service:latest
    restart: unless-stopped
    container_name: payroll-service
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: nexushr
      DB_USERNAME: postgres
      DB_PASSWORD: root
    depends_on:
      - postgres

  ai-insights-service:
    image: varshith1001/ai-insights-service:latest
    restart: unless-stopped
    container_name: ai-insights-service
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: root
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    depends_on:
      - postgres
      - redis

  notification-service:
    image: varshith1001/notification-service:latest
    restart: unless-stopped
    container_name: notification-service
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: nexushr
      DB_USERNAME: postgres
      DB_PASSWORD: root
      MAIL_HOST: smtp.gmail.com
      MAIL_PORT: 587
      MAIL_USERNAME: tonystarkbhaai@gmail.com
      MAIL_PASSWORD: ${MAIL_PASSWORD}docker 

  api-gateway:
    image: varshith1001/api-gateway:latest
    restart: unless-stopped
    container_name: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - auth-service
      - employee-service
      - payroll-service
      - ai-insights-service
      - notification-service

  frontend:
    image: varshith1001/frontend:latest
    restart: unless-stopped
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - api-gateway

volumes:
  postgres_data: