spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service
              uri: http://auth-service:8081
              predicates:
                - Path=/api/auth/**

            - id: employee-service
              uri: http://employee-service:8082
              predicates:
                - Path=/api/employees/**

            - id: dashboard-service
              uri: http://dashboard-service:8082
              predicates:
                - Path=/api/dashboard/**

            - id: attendance-service
              uri: http://attendance-service:8082
              predicates:
                - Path=/api/attendance/**

            - id: leave-service
              uri: http://leave-service:8082
              predicates:
                - Path=/api/leaves/**

            - id: performance-service
              uri: http://performance-service:8082
              predicates:
                - Path=/api/performance/**

            - id: payroll-service
              uri: http://payroll-service:8083
              predicates:
                - Path=/api/payroll/**

            - id: ai-insights-service
              uri: http://ai-insights-service:8084
              predicates:
                - Path=/api/ai/**

            - id: notification-service
              uri: http://notification-service:8085
              predicates:
                - Path=/api/notifications/**

          globalcors:
            cors-configurations:
              '[/**]':
                allowedOrigins:
                  - "http://localhost:5173"
                allowedMethods:
                  - GET
                  - POST
                  - PUT
                  - DELETE
                  - OPTIONS
                allowedHeaders: "*"

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      access: unrestricted

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
