apiVersion: v1
kind: ConfigMap

metadata:
  name: auth-config

data:
  DB_HOST: postgres-service
  DB_PORT: "5432"
  DB_NAME: nexushr_auth
  DB_USERNAME: postgres

  REDIS_HOST: redis-service
  REDIS_PORT: "6379"

  SERVER_PORT: "8081"