apiVersion: v1
kind: ConfigMap

metadata:
  name: payroll-config

data:

  DB_HOST: postgres-service
  DB_PORT: "5432"
  DB_NAME: nexushr_payroll
  DB_USERNAME: postgres

  SERVER_PORT: "8083"

  EMPLOYEE_SERVICE_URL: http://employee-service:8082