spring:
  application:
    name: ai-insights-service
  ai:
    openai:
      base-url: https://api.groq.com/openai/v1
      api-key: 
      chat:
        options:
          model: llama-3.1-8b-instant
  data:
    redis:
      host: localhost
      port: 6379
  datasource:
    url: jdbc:postgresql://localhost:5432/nexushr
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
  flyway:
    enabled: true

server:
  port: 8084
