spring:
  application:
    name: ai-insights-service
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4o-mini
  data:
    redis:
      host: localhost
      port: 6379

server:
  port: 8086